apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dev-pool-default
  namespace: common
  labels:
    strimzi.io/cluster: dev-kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  resources:
    limits:
      memory: 2Gi
  jvmOptions:
    -Xms: 512m
    -Xmx: 512m
  storage:
    type: persistent-claim
    class: longhorn
    size: 10Gi
    deleteClaim: false
    kraftMetadata: shared