apiVersion: observability.kaasops.io/v1alpha1
kind: VectorAggregator
metadata:
  name: vector-aggregator
spec:
  image: timberio/vector:0.43.0-alpine
  replicas: 1
  dataDir: /vector-data-dir
  env:
    - name: VECTOR_THREADS
      value: "2"
    - name: VECTOR_LOG
      value: "INFO"
    - name: VECTOR_GRACEFUL_SHUTDOWN_LIMIT_SECS
      value: "180"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: AWS_SECRET_ACCESS_KEY      
  api:
    enabled: true
    # playground: false
  internalMetrics: true
  resources:
    # requests:
      # memory: "256Mi"
      # cpu: "0.2"
    # limits:
      # memory: "1Gi"
      # cpu: "1"