apiVersion: observability.kaasops.io/v1alpha1
kind: VectorPipeline
metadata:
  name: vector-pipeline
spec:
  sources:
    kafka_source:
      type: "kafka"
      bootstrap_servers: "dev-kafka-cluster-kafka-bootstrap.common.svc.cluster.local:9092"
      topics: 
        - vector-test
      group_id: "vector-consumer-group"
      auto_offset_reset: "earliest"
      # 신뢰성을 위한 설정
      commit_interval_ms: 5000
      decoding:
        codec: json
    # internal_metrics:
      # type: internal_metrics
      # namespace: cluster-config
      # scrape_interval_secs: 5
    
  transforms:
    format_json:
      inputs: 
        - kafka_source
      type: remap
      source: |
        del(.topic)
        del(.source_type)
        del(.partition)
        del(.offset)
        del(.headers)
        . = encode_json(.)
        
  sinks:
    s3_sink:
      type: "aws_s3"
      inputs: 
        - format_json
      bucket: "vector-test"
      endpoint: "http://common-minio-hl.common.svc.cluster.local:9000"  # MinIO endpoint
      region: "ap-northeast-2"
      key_prefix: "logs/dt=%Y-%m-%d/"
      acknowledgements:
        enabled: true  # ACK 활성화
      filename_append_uuid: true
      filename_time_format: "%s"
      compression: "none"
      encoding:
        codec: "text"
      
      # 버퍼 설정
      buffer:
        type: "memory"
        max_events: 500
        when_full: "block"
      
      # 배치 설정
      batch:
        max_bytes: 10485760  
        timeout_secs: 60
    # prometheus:
      # type: prometheus_exporter
      # inputs:
        # - internal_metrics
      # address: 0.0.0.0:9598