apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-

resources:
  - ./common-agent.yaml
  - ./common-log-pipeline.yaml
  - ./cluster-config-agent.yaml
  - ./cluster-config-log-pipeline.yaml