apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-eck
spec:
  version: 7.17.28
  count: 1
  elasticsearchRef:
    name: dev-elasticsearch-eck
    namespace: common
  podTemplate:
    spec:
      containers:
      - name: kibana
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true