controller:
  name: controller
  kind: DaemonSet
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  extraArgs:
    enable-ssl-passthrough: true # 기능 활성화 / 실제는 annotation에서 동작
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.30.1.101
  
  # 특정 네임스페이스만 적용할 경우
  # scope:
    # namespaceSelector: ingress=common