controller:
  name: controller
  kind: Deployment # DaemonSet의 경우는 leader / follower 형태로 운영되는 구조라 
  replicaCount: 1
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  # extraArgs:
    # enable-ssl-passthrough: true
  config:
    enable-real-ip: "true" # X-Forwarded-For 헤더 값을 $remote_addr로 변경
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true" # 거쳐온 모든 IP 추적
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.30.1.101
  
  # 특정 네임스페이스만 적용할 경우
  # scope:
    # namespaceSelector: ingress=common