controller:
  name: controller
  kind: Deployment # DaemonSet의 경우는 leader / follower 형태로 운영되는 구조라 
  replicaCount: 1
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  # extraArgs:
    # enable-ssl-passthrough: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.30.1.101
  
  # 특정 네임스페이스만 적용할 경우
  # scope:
    # namespaceSelector: ingress=common