# 초기 pvc를 고정하기 위한 설정

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-redis-master
  namespace: cluster-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn