apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: schema-registry
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  environment: dev
          - list:
              elements:
                - env: dev
                  chart_repo: registry-1.docker.io/bitnamicharts
                  chart_name: schema-registry
                  chart_version: "25.1.9"
        
  template:
    metadata:
      name: "{{.env}}-schema-registry"
    spec:
      project: common
      sources:
        - repoURL: git@github.com:yahwang/yahwang-k8s-manifest.git
          targetRevision: HEAD
          ref: values
        - repoURL: "{{.chart_repo}}"
          targetRevision: "{{.chart_version}}"
          chart: "{{.chart_name}}"
          helm:
            valueFiles:
              - "$values/apps/schema-registry/overlays/{{.env}}/values-override.yaml"
      destination:
        server: "{{.server}}"
        namespace: common
      syncPolicy:
        automated:
          # prune: true
          selfHeal: true
        syncOptions: 
          - ServerSideApply=true # Too long: must have at most 262144 bytes 이슈 해결
          - CreateNamespace=true