---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vector-consumer
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            server: https://kubernetes.default.svc

  template:
    metadata:
      name: "{{env}}-vector-consumer"
    spec:
      project: platform
      sources:
        - repoURL: git@github.com:yahwang/yahwang-k8s-manifest.git
          targetRevision: HEAD
          path: apps/vector-consumer/overlays/{{env}}
      destination:
        server: "{{server}}"
        namespace: platform
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
