apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  name: vector-pipeline
  labels:
    vector-role: vector-consumer
spec:
  sources:
    kafka_source:
      type: "kafka"
      bootstrap_servers: "common-kafka-kafka-bootstrap.common.svc.cluster.local:9092"
      topics: ["vectorTest"]
      group_id: "vector-consumer-group"
      auto_offset_reset: "earliest"
      # 신뢰성을 위한 설정
      commit_interval_ms: 5000
    
  transforms:
    format_json:
      inputs: ["kafka_source"]
      type: remap
      source: |
        del(.topic)
        del(.source_type)
        del(.partition)
        del(.offset)
        del(.headers)
        . = encode_json(.)  # 이벤트를 JSON 문자열로 인코딩
        
  sinks:
    s3_sink:
      type: "aws_s3"
      inputs: ["format_json"]
      bucket: "vector-test"
      endpoint: "http://common-minio-hl.common.svc.cluster.local:9000"  # MinIO endpoint
      region: "ap-northeast-2"
      key_prefix: "logs/dt=%Y-%m-%d/"
      acknowledgements:
        enabled: true  # ACK 활성화
      filename_append_uuid: true
      filename_time_format: "%s"
      compression: "none"
      encoding:
        codec: "text"
      
      # S3 인증
      # auth:
        # access_key_id: ""
        # secret_access_key: ""
      
      # 버퍼 설정
      buffer:
        type: "disk" # memory
        when_full: "block"
        max_size: 268435488  # disk 사용 시
      
      # 배치 설정
      batch:
        max_bytes: 10485760  
        timeout_secs: 60    