---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: datahub-oauth-secret
  namespace: common
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgBNeW7FF/b0eAA9zqHDM7Y5bEkxnbFkonYHbMab8446tXpWqE9oZOualbJ19HZ1DUMId1CCl3NsYRX9uK6SCMJfZ45WiAG5oEIKJbzlBktSAqi7FcoBV3oToNDFUdJBVRNoblWN6Mm4HuNY1JfsITHO8Ah45CUW174qRkaCYND6fDj6RkA2WKUMXL+zkRLtnbyfTd53XLuixpq6iMcec0cOvtemqQzLTfeM0j1IUie1fW+N/iK0mU6HVpbgjK6O4sEF86IdlZ21GVPqL6sJ7xiasYVrmeLr4QG6LYUITOQZZ1BPVaZCutO+5yU/khJzQJ+HRFzLvXbY6t/tzXej66N/1zZsZxzaz1vVcSiecmH1oVJVQ10HSB7xsJ/ubCHIJh58563/QB+cT69auuhOptXSfi1PwqRwfoNN52iLQRFE4MndswmRtnLFFi+Amze6WpauZ/VYWCKWthbZu+/YUMtUbdSie+1v/Ouijk2yuBq0qd4rAEnlwUhor1xP2pDUUGnvHbAGXxE8WMd73wFlE+YaIUYZwmbp0flMKVgMQXXAtNABSH537iPrTYyhQZ2o41RjGCtCoEnLjWJXefVTo7HsvIIXqiJf09kMSGwf3i/wnhh9Dud7go6GcZjB+f3FrpypN+rPFWKZesmx57r7X/VXKgcnUiYe9VA9WlzeYM+JmdKb+Y/HBTMWf56TlfSdBj42TpvoKtNyAbU48emJXQxBIH0SRn1TYw37fYefzkdFJQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: datahub-oauth-secret
      namespace: common
    type: Opaque
