---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datahub-oauth-secret
  namespace: common
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgAlUpT3Gr7/v5Cthi7ACxB2UJOsm6x1uWBMyjf5rzZqanBGHvlFhz2dVsRrMF9hSRH26K+NHgHDK0o6W9YwvpcPkrWJ9shyJz4hNVXDazqIxCFHETRNM0x980EkVpJma18rkIunKiGImQ/YVBhdC088Hi74YApF4PRZgftFN5IyX1ZnqbFfP53oW6ePtdQkX4oLpq1xmdOd3EopG/KMnQL/yuhmoxon3QMpXoadf/kKlVxk/KuVpyb8BlCtAchI45g25JpFSUiE7IqZUiHZGDflnA9Qi3vD+qzote53C05L2tpgLvEKqYi0ElYm0RYdAr1LfpU1tGDE2nrz+fK57s3TJRyFBUUEqy6vWnSkCPb1/vgZVJJhGXlMPIP06k1BKEKJmdUVJ2668ws8AiDL6squlWT1aG+VJJFHc/JEn87KllaI/7XVsDKjIlWmx2H3ALNI/XSaxRri29VIQP+GVysOQFwxi0h4eU7vf6zpkegzybO808PuoFfiIK6ZRlPtA0cbAL4DLeoAW6/asR5tuiFOTyIGIdyt5illeVLSsAP2wy8RgdDAWjGLTbHJD1V4HrsSw2Fl35lJoiV8g8YHVZ718lt9oiQkSCW5cIHERBT3KE0pYns73u9aWAm1JmfiCuFubYehB2Qo1CIS3jeXFcf3Ncp+ds3DG4y82ovxVDd6Al5SnxvQfha/gfBk10JM3xbXzkoAqZOYkQHPhJBuoOHdtRUmq5OP5hxMqsCdesW0Xw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datahub-oauth-secret
      namespace: common
    type: Opaque
