---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: es-superuser-secret
  namespace: common
spec:
  encryptedData:
    password: AgAv5X1HJq8XO2T3W0NdBe7b0fizsAV4Fpf+0s9TjmUxTtOsShG3TMT0tZYTQVMa0FfJL05mE79JyGWZXMf9Iqd+dHXzwXk3rP7Yz9vMZOHBo0ISm/4Hiq+KtzGZv8sfu6KZ8x8AV2nEtnfxl1alqgNnQ/xv+urNFeTh6Wpz45Lb+NPznLKJaJk97X7fqIGT2qxORIOKKdot7ZCFHjNQg+1qknELV+Xq3TCbuxmPGmOccBmPbtnJTVUuNtzZQNSAc8M4U1pLNZxJSidKSeSdhSuPgoLUYCYwljqiFnpsRlqx2dSvCdJYMJjFXwV0q/k05x/n17lWov9Tb3XSfqxE0ZXn6TiCHe64q0zBgvwU4ESEKudKpRuiIouT2vl3kG3g5eZb30Y8P6O6OgozFmV7M0tYxkCnou8EGZDXOzce0GnDb+HXzV+5Ct7Sk8sE0hhcwJdQrU6HcWi2X3F9Ty+0Wk8sr9dNqon0IPzTdWW+tysIzD8VEBcsZNrpqO+rviermsXmMLVvywAdRnsGH2dthITqIfqm6Ap/jecyUPMNdNf/1LJDTQP+M6ce+BEwQutvFI1nWs3KpcpnHv4e/royybD2Noq4neVi/lbbDr+5WE72D8Cp2BTPpg6iqwBFnV1TKlhzClnhO7GMUPcxHA2WkPTbxy3eMttQzbiKHAjK9X+pYrn/lG0qcFxDSrgkW5ve7PSZWNKMyuzZNpj4JIBeeOk=
    roles: AgAbxwPQY4BzfrRRqSCzR9H6yEt48M2xdPXa6t9/1hEy2KvlfzwHDVAptDqRXfAZKcWQroKhESsE0CPEYkb/kdh2Ed0Rr+GRC8getYZMHaXQPfSjqDyJDWFcvdJ6XhqHL5d8xRBUKQEQI4oGDTwskEaT5SeW/WTbzQHQ5i6uryDw+a8lzoN86aCwIs4bKQ10bRW+Z4BkWDbFBS0Czr3BftQ9fGzYjeRWn7jBmP4SivEsK5UpqRI0A+haGqFE/8edDehViYbHVQMGYnkzV3dGd+aFznQZvuzBX5ABlPhnIPPaR3q3dQvVzZ8Wt2i61kMNvFFh+Vy5gn/PM2pW4XtprmUrIPUeiWXbJ1jo2cjDBylts9vMrazfEPnHW9YCnqSj9DOvDk+gatcS9kWHXh4MfY+Zr9ev4pHREUMBLdF3aLXTozGPBnzntbDzx+y9N0hJvyZ4OzfLvh5RN0mjAIxiv1pv8h2BLN1XzzGLievr+YCyWcc+Km+wbaHMJVLIWpDFjF60SdxpfG7mfhd8r5LwiDAfK6yvI9UQKVRPiCGJkztN3ZC144h1PALRDoArEieA19xsNYehWlt/ntlJGZjvJlMl9bgs6ysN84BeWF38qEXruVWuueh+LZ6yteKWOO+hSpdLACX5+rXFxBClCgtxxBFy/P447Krl0FZYnOVUcyCvMlomi9G+0gxRIsjwPs7v8wLsGKciP7UJmyieBWjJ4rLUsTLqZh9d
    username: AgBGaPR4F/inRbt2QXnBwI/94kq45MByFUfsTf3BAWm6Wi1g2SW+2/tyjRZm8bFMlEqCn4uX9A0fi7jasVALxymQNWlejh4HkqRmlh74e0EpbgkV/FpxShXOWI/pbhpZZF71oa0iVWL+vmsIcskLFeryV9nVQzFzZ9U+PMOh4ePNdbKfpEinm/2+fDLwwcIXJAId4k1vg3sZNiTibBlLlB/fbbFx2UF4MaJSM92AFYL6WNFaBrVDt6JurNieEJSE0pdkyHbUOwZQ6dYd7iGPkswWbmZJlu2zVpe3DojR1ie6ICDzZdSpVGMWcQSqFck4JgYQ1wpIeZH+/N29NDkPuTC+nFIt4XNXdAE4Smjk7XTZWWKYmVsca0o57qOxTifPkJo10xUIiEIcG4fzJjT9g0G07COdMxzz33rb55HXDhTmMhkSqbORCqSVGoKg/JVT61r3joR92yUbLtteMCDBkzPH6Xmk8Sh0uzf74JdlgRx9tjQXj/G6xnagJ/46QxbMQVyXK5qbcA9QsGcthN7gJwJqpjX511zMJv6aKdXrSmB7zk+WS5xv5FTa5vZiSI2kt3coFTSZe3Iq4OMIvYDG2dmDgxWhwzlTzhTOkefVjf4KVxG2swMFFwR5FPGy9qBP9OxYeBOVqLxc7O5IhvWir3DooXfxqEkOjekRM5r/Jgr3BAErkeWzc0QnPPw/PQpaim8zhsqIwEBV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: es-superuser-secret
      namespace: common
    type: Opaque
