---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: airflow-metadata-conn-secret
  namespace: common
spec:
  encryptedData:
    connection: AgBX3x+2HXdiQWCZFMHIG5itq531gKq8d3Ozp6tzUAsrjsCFxW5MKjSIF2jj9HWTATTBWnyZRqoRKE+txRqaNU+yQoFIAls3DLuzG/oJU74Ec3bmk0WvKHB5rOZOJQ8gQurZMk6jXyjjjBz51yMOwVXvS6bCYCxpfjz4w6TJdXNis6SjdoylusVJGeFdLPBdxTxG+FGjeXHwl7l9lBoB67YbkXO40M3Grh9jOez1FaB1KasV2IfzI8545W9SNUje1//ZfQC77rgUCYS0TytOekOjMuWTIeMe/oeW0XDaiTqVpM1eP9lWcY/HEpispWBrEa3DPCgcff2JyjwgoKsIHLrUxwz6WK7Ij4NVmzhn6MN+nqWgFxo7GeVgKb2W1snnNSZHxiKGwH8u2VjCZ45UJOvjMfIL3H4MprclL2WrFEMjyutdAaNcX0dLGQw/N2NLLIpjAP+dNDY1MWqgPAlRTFBky0SVv51g3jn9eS3wyZif5uFm55HIsSXQq96Mlim6ZDYKNM5Sxb+Dxc3vXQJ5FGO7H+kOwSFxEfIuCuSoCUyFjK2VyjUXzdn3AELlxxms8ZaS4xVl17MXp31ia7w3/MyTGNfdsRTc/mXUfqHGH5TDCkGJDDA9MWXmBhpcCPgE5M1YcpLCndwgV92u9RRmw/fLkP8S8uP+hpARAilG6kRF/SdMi9GnQtB5wkM2H7lkMLE3EY3/Kyd4WJoJ6a2nZCIAZtDVkCJHWLWV5q/7YBtOQc4g9j4/FRRMl5oJ+0/BczoMSI3JnMYRcXmi8j9mQJWUeyFfi0pIqidiao3sU2Q92irxNkcbqMiDx7wR3m8zZgXiQiUl0HA1iZW5tGE/sQn3w+Gx///Oc/KusCx7mJ0ScaTzPDyxsVzNtAtFgJ60UWKX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: airflow-metadata-conn-secret
      namespace: common
    type: Opaque
